### ISSUE TITLE
ssgしたファイルをローカルで確認すべがない

### ISSUE THREAD

**Issue by tamaitomoaki** [konel-inc/next-ts-template#10]
調べたら、
https://yarnpkg.com/package/serve
がよさそうで、
インストールしたら
npx serve out
で閲覧可能。

デフォルトで入れておくと良いのでは？
もしくは、ssg用のテンプレートを分ける？

**Comment by jayq8805** [comment]
@tamaitomoaki モジュールは、Node環境下でhttpサーバーを簡易的に開くモジュールです。
普段Workspace内に設置するのではなく、ローカルにGlobal設置することで仕様するのが一般的かと。
```
yarn global add serve
```

ServeモジュールまでPackageに記録すると、無用な設置になるので、Out結果をローカルで試したい場合は、　ご自身の環境で実行してください。（Publish環境によっては、セキュリティーの問題もありますので要注意！）

**Comment by tamaitomoaki** [comment]
@jayq8805 
なるほど、承知しました！
