### ISSUE TITLE
機能別ブランチの使用方法の記述が不足

### ISSUE THREAD

**Issue by tamaitomoaki** [konel-inc/next-ts-template#3]
styled componentを使用したい場合に、
branch: styled-componentをどのように使用すればよいか
手順が不足している

手順
`yarn create next-app --example https://github.com/konel-inc/next-ts-template [APP_NAME]`を実行時に、ブランチを指定する
(例)
`yarn create next-app --example https://github.com/konel-inc/next-ts-template/tree/styled-components [APP_NAME]`

**Comment by ogiyasu** [comment]
notionに記述
