### ISSUE TITLE
デフォルト設定で、"react/prop-types"が有効になっている意味は？

### ISSUE THREAD

**Issue by tamaitomoaki** [konel-inc/next-ts-template#9]
"react/prop-types"がデフォルトで有効になっていますが、
軽くしたべた感じ、typescriptと役割がかぶるらしいので
offにして作業進めました。

こちら、有効になっている意味はあるのでしょうか？

**Comment by tamaitomoaki** [comment]
ssgの時にしか発生しない？

**Comment by jayq8805** [comment]
@tamaitomoaki mainに反映します。
